version: 0.0
os: linux

# Make sure that "destination" is not same for two different Code Deploy Groups/Deployments.
files:
  - source: /
    destination: /home/ubuntu/anupam

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 20
      runas: ubuntu
