version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Running tests `date`
      - mvn clean install
  post_build:
    commands:
      - echo Building project started on `date`
      - mvn package
artifacts:
  files:
    - target/my-java-app-1.0-SNAPSHOT.jar
