version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      yum install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Running tests `date`
      - mvn install
      - mvn test
  post_build:
    commands:
      - echo Building project started on `date`
      - mvn install package
artifacts:
  files:
    - target/my-java-app-1.0-SNAPSHOT.jar
