version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo installing maven...
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Running tests `date`
      - mvn install
  post_build:
    commands:
      - echo Building project started on `date`
      - mvn package
artifacts:
  files:
    - target/my-java-app-1.0-SNAPSHOT.jar
