apiVersion: v1
kind: Service
metadata:
  name: java-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30007
